name: Extract Chrome and Upload to Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Set Bablosoft version info
        id: vars
        run: |
          echo "version=28.8.1" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Download FastExecuteScript ZIP
        run: |
          curl -L -o FastExecuteScript.zip "http://downloads.bablosoft.com/distr/FastExecuteScriptProtected64/${{ steps.vars.outputs.version }}/FastExecuteScriptProtected.x64.zip"

      - name: Get highest Worker.xx folder in ZIP
        id: get_worker
        run: |
          folders=$(unzip -Z1 FastExecuteScript.zip | grep -oE '^Worker\.[0-9]+/' | sort -Vr | uniq)
          highest=$(echo "$folders" | head -n1 | sed 's:/$::')
          echo "worker=$highest" >> $GITHUB_OUTPUT
          echo "Found highest worker: $highest"

      - name: Extract full chrome folder only
        run: |
          mkdir extracted_chrome
          files=$(unzip -Z1 FastExecuteScript.zip | grep "^${{ steps.get_worker.outputs.worker }}/chrome/")
          for file in $files; do
            target_file=${file#${{ steps.get_worker.outputs.worker }}/}
            unzip -j -q FastExecuteScript.zip "$file" -d "extracted_chrome/$(dirname "$target_file")"
          done

      - name: Get Chrome version from manifest file
        id: chrome_version
        run: |
          # Find the manifest file inside extracted_chrome/chrome
          manifest_file=$(find extracted_chrome/chrome -maxdepth 1 -type f -name '*.manifest' | head -n1)
          echo "Manifest file found: $manifest_file"
          chrome_ver=$(basename "$manifest_file" .manifest)
          echo "chrome_version=$chrome_ver" >> $GITHUB_OUTPUT

      - name: Zip extracted chrome folder silently with custom name
        run: |
          cd extracted_chrome
          zip -rq ../chrome_${{ steps.chrome_version.outputs.chrome_version }}.zip chrome

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "BAS Engine ${{ steps.vars.outputs.version }} - Chrome ${{ steps.chrome_version.outputs.chrome_version }}"
          tag_name: "${{ steps.vars.outputs.date }}"
          files: chrome_${{ steps.chrome_version.outputs.chrome_version }}.zip
          body: |
              BAS Engine Version ${{ steps.vars.outputs.version }}  
              Chrome Version ${{ steps.chrome_version.outputs.chrome_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
